import { Inter } from "next/font/google";
import NavBar from "@/app/components/NavBar";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <NavBar />
        <main className="px-10 py-20 max-w-2xl mx-auto sm:flex-row justify-center ">
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}